// Custom hooks for Preact components
export { useDebounce } from './useDebounce';
export { useThrottle } from './useThrottle';
export { useIntersectionObserver } from './useIntersectionObserver';
export { useMediaQuery } from './useMediaQuery';
export { useLocalStorage } from './useLocalStorage';
export { useClickOutside } from './useClickOutside';
export { useFocusTrap } from './useFocusTrap';
export { useReducedMotion } from './useReducedMotion';
export { usePerformanceMonitor } from './usePerformanceMonitor';
export { useScrollLock } from './useScrollLock';
export { usePrevious } from './usePrevious';
export { useAsyncEffect } from './useAsyncEffect';